In [ ]:
import tensorflow as tf

In [ ]:
tf.__version__


'2.11.0'

In [ ]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

In [ ]:
a = tf.constant(10)
a

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
b = tf.constant(10.2)
b

<tf.Tensor: shape=(), dtype=float32, numpy=10.2>

In [ ]:
c = tf.constant("Indian AI")
c

<tf.Tensor: shape=(), dtype=string, numpy=b'Indian AI'>

In [ ]:
d = tf.constant(True)
d

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
import numpy as np

In [ ]:
np_arr = tf.constant(np.array([1,2,3,4]))
np_arr

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

In [ ]:
t_1d = tf.constant([1,2,3,4])
t_1d

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
t2d = tf.constant([[1,2],[3,4]])
t2d

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
t2d_1 = tf.constant([1,2,3,4], shape=(2,2), dtype="float32")
t2d_1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [ ]:
t3d_1 = tf.constant([[[1,2],[2,3],[3,4]]], dtype="float32")
t3d_1

<tf.Tensor: shape=(1, 3, 2), dtype=float32, numpy=
array([[[1., 2.],
        [2., 3.],
        [3., 4.]]], dtype=float32)>

In [ ]:
type(t3d_1)

tensorflow.python.framework.ops.EagerTensor

In [ ]:
t3d_1.shape

TensorShape([1, 3, 2])

In [ ]:
t_1d.numpy()

array([1, 2, 3, 4], dtype=int32)

In [ ]:
t3d_1.dtype

tf.float32

In [ ]:
tf.constant([1, 24.3, "Indian"])