<a href="https://colab.research.google.com/github/ravindrakush11/Deep-Learning/blob/main/TF_Variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
tf.Variable(1)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

In [ ]:
a = tf.Variable([1,2,3,4])
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
a.name,



('Variable:0',)

In [ ]:
a.shape

TensorShape([4])

In [ ]:
a.dtype

tf.int32

In [ ]:
a.numpy()

array([1, 2, 3, 4], dtype=int32)

In [ ]:
type(a)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [ ]:
t1 = tf.Variable([1.2, 4.4, 5, 6])
t1

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1.2, 4.4, 5. , 6. ], dtype=float32)>

In [ ]:
t2 = tf.Variable(['a','b','c','d'])
t2

<tf.Variable 'Variable:0' shape=(4,) dtype=string, numpy=array([b'a', b'b', b'c', b'd'], dtype=object)>

In [ ]:
t3 = tf.Variable([True, False])
t3

<tf.Variable 'Variable:0' shape=(2,) dtype=bool, numpy=array([ True, False])>

In [ ]:
t4 = tf.Variable([3+5j])
t4

<tf.Variable 'Variable:0' shape=(1,) dtype=complex128, numpy=array([3.+5.j])>

In [ ]:
t5 = tf.constant([1,2,3,4])
t5

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
tf.Variable(t5)

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
t6 = tf.Variable([[1,2], [3,4]])
t6

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
t7 = tf.Variable([[4,5], [8,10]], shape =(2,2))
t7

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[ 4,  5],
       [ 8, 10]], dtype=int32)>

In [ ]:
t1

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1.2, 4.4, 5. , 6. ], dtype=float32)>

In [ ]:
tf.reshape(t1, (2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.2, 4.4],
       [5. , 6. ]], dtype=float32)>

In [ ]:
tf.argmax(t7)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1])>

In [ ]:
tf.argmax(t7).numpy()

array([1, 1])

In [ ]:
tf.convert_to_tensor(t1)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.2, 4.4, 5. , 6. ], dtype=float32)>

In [ ]:
tf.convert_to_tensor(t7)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 4,  5],
       [ 8, 10]], dtype=int32)>

In [ ]:
t1.assign([10,20, 30, 40])
t1

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([10., 20., 30., 40.], dtype=float32)>

In [ ]:
t1.assign_add([1,4,8,9,])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=float32, numpy=array([11., 24., 38., 49.], dtype=float32)>

In [ ]:
a.assign([1,4,8,9,7])

In [ ]:
a.assign([5.2, 3.7, 1.2, 10, 5])